### ISSUE TITLE
Feedback with the movement

### ISSUE THREAD

**Issue by imro1** [EliasKonsta/Overseas-Game#2]
I saw that your main character's movements are a bit off because he is turning the whole body.
I recommend you using this:

if (Greenfoot.isKeyDown("a")) {
            setRotation(180);
        }
if (Greenfoot.isKeyDown("d")) {
            setRotation(360);
        }
etc...

Hope this will help you to better your game!

Imran Maslianov.

**Comment by sheldongree** [comment]
Thank you for your suggestion, I will implement the code. I still have some problems fixing it, but I will try to fix as soon as possible.
